FROM python:3.8
RUN apt update -y && apt install -y iputils-ping
RUN mkdir -p code
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip3 install -r /code/requirements.txt
#RUN pip install "uvicorn[standard]"
COPY ./app /code/app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]